apiVersion: ecs.aws.crossplane.io/v1alpha1
kind: TaskDefinition
metadata:
  name: cp-nginx
spec:
  forProvider:
    family: cp-nginx
    region: us-west-2
    containerDefinitions:
    - cpu: 0
      portMappings:
      - containerPort: 80
        hostPort: 80
        protocol: tcp
      image: public.ecr.aws/nginx/nginx:latest
      name: web
    cpu: '8192' # 8 vCPU
    # cpu: '16384' # 16 vCPU
    memory: '32768' # 32 GB
    networkMode: awsvpc
    requiresCompatibilities:
    - FARGATE
  providerConfigRef:
    name: aws-provider-config